### ISSUE TITLE
Please create an AppData file for FourTerm

### ISSUE THREAD

**Issue by hughsie** [lzap/fourterm#1]
Please consider writing and installing an AppData file with the application description and some screenshots, else FourTerm looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by lzap** [comment]
I am pulling out the package from fedora, this project is unmaintained now. No time, migrated to i3.
