### ISSUE TITLE
unable to build fourterm on Fedora 25

### ISSUE THREAD

**Issue by rosset** [lzap/fourterm#3]
- unable to build fourterm on Fedora 25

[filiperosset@rosset-laptop fourterm]$ fedpkg local

Executando (%prep): /bin/sh -e /var/tmp/rpm-tmp.oOqbTZ
+ umask 022
+ cd /home/filiperosset/rpmbuild/extras/fourterm
+ cd /home/filiperosset/rpmbuild/extras/fourterm
+ rm -rf fourterm-1.0.6
+ /usr/bin/gzip -dc /home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd fourterm-1.0.6
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executando (%build): /bin/sh -e /var/tmp/rpm-tmp.ogc9FK
+ umask 022
+ cd /home/filiperosset/rpmbuild/extras/fourterm
+ cd fourterm-1.0.6
+ waf configure --with-gtk3 --prefix=/usr
Setting top to                           : /home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6 
Setting out to                           : /home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/build 
Checking for 'gcc' (C compiler)          : /usr/lib64/ccache/gcc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'gobject-2.0'               : yes 
Checking for 'gthread-2.0'               : yes 
Checking for program 'valac-0.8'         : not found 
Checking for program 'valac'             : /usr/bin/valac 
Checking for valac version >= (0, 8, 0)  : (0, 34, 2) 
Checking for program 'msgfmt'            : /usr/bin/msgfmt 
Checking for program 'perl'              : /usr/bin/perl 
Checking for program 'intltool-merge'    : /usr/bin/intltool-merge 
Checking for header locale.h             : yes 
Checking for program 'valac-0.13'        : /usr/bin/valac 
Checking for valac-0.13 version >= (0, 13, 2) : (0, 34, 2) 
Checking for 'glib-2.0'                       : yes 
Checking for 'gobject-2.0'                    : yes 
Checking for 'gthread-2.0'                    : yes 
Checking for 'gee-1.0'                        : yes 
Checking for 'gtk+-3.0'                       : yes 
Checking for 'vte-2.90'                       : yes 
'configure' finished successfully (0.102s)
+ waf
Waf: Entering directory `/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/build'
[ 1/25] Compiling po/fr.po
[ 2/25] Processing valac: src/about.vala src/check-button.vala src/check-menu-item.vala src/colors.vala src/color-button.vala src/config-file.vala src/default-dialog.vala src/font-button.vala src/icons.vala src/image-menu-item.vala src/main.vala src/main-window.vala src/menu-bar.vala src/menu-item.vala src/message-dialog.vala src/parameters-window.vala src/parameter-box.vala src/settings.vala src/spin-button.vala src/grid-manager.vala src/terminal.vala src/matchers.vala -> build/about.c build/check-button.c build/check-menu-item.c build/colors.c build/color-button.c build/config-file.c build/default-dialog.c build/font-button.c build/icons.c build/image-menu-item.c build/main.c build/main-window.c build/menu-bar.c build/menu-item.c build/message-dialog.c build/parameters-window.c build/parameter-box.c build/settings.c build/spin-button.c build/grid-manager.c build/terminal.c build/matchers.c
Compilation succeeded - 20 warning(s)

gee-1.0.vapi:328.4-328.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-1.0.vapi:330.4-330.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-1.0.vapi:338.4-338.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gee-1.0.vapi:340.4-340.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:21.24-21.32: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:22.30-22.38: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:23.24-23.32: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:24.23-24.31: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:25.24-25.32: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:30.29-30.37: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:26.22-26.30: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:27.23-27.31: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/colors.vala:104.9-104.17: warning: Gdk.Color has been deprecated since 3.14
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/main-window.vala:33.7-33.23: warning: Access to static member `MainWindow.window_count' with an instance reference
      this.window_count++;
      ^^^^^^^^^^^^^^^^^
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/main-window.vala:66.24-66.31: warning: Gtk.VBox has been deprecated since 3.2. Use Box
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:28.21-28.29: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/icons.vala:29.25-29.33: warning: Gtk.Stock has been deprecated since 3.10
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/main-window.vala:193.8-193.24: warning: Access to static member `MainWindow.window_count' with an instance reference
    if(this.window_count < 2)
       ^^^^^^^^^^^^^^^^^
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/main-window.vala:199.7-199.23: warning: Access to static member `MainWindow.window_count' with an instance reference
      this.window_count--;
      ^^^^^^^^^^^^^^^^^
/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/src/color-button.vala:22.5-22.14: warning: Gtk.ColorButton.color has been deprecated since 3.4. Use rgba

[ 3/25] Compiling build/spin-button.c
[ 4/25] Compiling build/parameters-window.c
[ 5/25] Compiling build/menu-item.c
[ 6/25] Compiling build/menu-bar.c
[ 7/25] Compiling build/icons.c
[ 8/25] Compiling build/color-button.c
[ 9/25] Compiling build/about.c
[10/25] Compiling build/colors.c
[11/25] Compiling build/message-dialog.c
[12/25] Compiling build/parameter-box.c
color-button.c: In function 'color_button_construct':
color-button.c:48:2: warning: 'gtk_color_button_set_color' is deprecated: Use 'gtk_color_chooser_set_rgba' instead [-Wdeprecated-declarations]
  gtk_color_button_set_color ((GtkColorButton*) self, &_tmp0_);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:74:0,
                 from color-button.c:7:
/usr/include/gtk-3.0/gtk/gtkcolorbutton.h:89:12: note: declared here
 void       gtk_color_button_set_color      (GtkColorButton *button,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~

[13/25] Compiling build/terminal.c
[14/25] Compiling build/grid-manager.c
colors.c: In function 'colors_active_palette':
colors.c:47:73: warning: passing argument 1 of '_vala_array_dup1' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   _tmp2_ = (COLORS_solarized_light_palette != NULL) ? _vala_array_dup1 (COLORS_solarized_light_palette, G_N_ELEMENTS (COLORS_solarized_light_palette)) : ((gpointer) COLORS_solarized_light_palette);
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
colors.c:26:18: note: expected 'GdkColor * {aka struct _GdkColor *}' but argument is of type 'const GdkColor * {aka const struct _GdkColor *}'
 static GdkColor* _vala_array_dup1 (GdkColor* self, int length) {
                  ^~~~~~~~~~~~~~~~
colors.c:61:72: warning: passing argument 1 of '_vala_array_dup2' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   _tmp4_ = (COLORS_solarized_dark_palette != NULL) ? _vala_array_dup2 (COLORS_solarized_dark_palette, G_N_ELEMENTS (COLORS_solarized_dark_palette)) : ((gpointer) COLORS_solarized_dark_palette);
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
colors.c:31:18: note: expected 'GdkColor * {aka struct _GdkColor *}' but argument is of type 'const GdkColor * {aka const struct _GdkColor *}'
 static GdkColor* _vala_array_dup2 (GdkColor* self, int length) {
                  ^~~~~~~~~~~~~~~~
colors.c: In function 'colors_parse':
colors.c:146:2: warning: 'gdk_color_parse' is deprecated: Use 'gdk_rgba_parse' instead [-Wdeprecated-declarations]
  _tmp2_ = gdk_color_parse (_tmp0_, &_tmp1_);
  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkcairo.h:26:0,
                 from /usr/include/gtk-3.0/gdk/gdk.h:33,
                 from colors.c:7:
/usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h:79:11: note: declared here
 gboolean  gdk_color_parse     (const gchar    *spec,
           ^~~~~~~~~~~~~~~

[15/25] Compiling build/settings.c
[16/25] Compiling build/image-menu-item.c
image-menu-item.c: In function 'image_menu_item_construct':
image-menu-item.c:51:2: warning: 'gtk_image_menu_item_set_use_stock' is deprecated [-Wdeprecated-declarations]
  gtk_image_menu_item_set_use_stock ((GtkImageMenuItem*) self, TRUE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:265:0,
                 from image-menu-item.c:7:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:97:12: note: declared here
 void       gtk_image_menu_item_set_use_stock     (GtkImageMenuItem *image_menu_item,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
image-menu-item.c: In function 'image_menu_item_get_type':
image-menu-item.c:97:3: warning: 'gtk_image_menu_item_get_type' is deprecated: Use 'gtk_menu_item_get_type' instead [-Wdeprecated-declarations]
   image_menu_item_type_id = g_type_register_static (gtk_image_menu_item_get_type (), "ImageMenuItem", &g_define_type_info, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:265:0,
                 from image-menu-item.c:7:
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h:76:10: note: declared here
 GType    gtk_image_menu_item_get_type          (void) G_GNUC_CONST;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

[17/25] Compiling build/font-button.c
[18/25] Compiling build/check-button.c
[19/25] Compiling build/check-menu-item.c
about.c: In function 'about_construct':
about.c:82:30: error: 'DATADIR' undeclared (first use in this function)
   _tmp3_ = g_build_filename (DATADIR, "/icons/hicolor/128x128/apps/fourterm.png", NULL);
                              ^~~~~~~
about.c:82:30: note: each undeclared identifier is reported only once for each function it appears in

menu-bar.c: In function 'menubar_instance_init':
menu-bar.c:404:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp0_ = image_menu_item_new (ICONS_ABOUT, NULL);
  ^~~~~~
menu-bar.c:407:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp1_ = image_menu_item_new (ICONS_PREFERENCES, NULL);
  ^~~~~~
menu-bar.c:410:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp2_ = image_menu_item_new (ICONS_CLEAR, NULL);
  ^~~~~~
menu-bar.c:413:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp3_ = image_menu_item_new (ICONS_COPY, NULL);
  ^~~~~~
menu-bar.c:416:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp4_ = image_menu_item_new (ICONS_PASTE, NULL);
  ^~~~~~
menu-bar.c:419:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp5_ = image_menu_item_new (ICONS_SELECT_ALL, NULL);
  ^~~~~~
menu-bar.c:423:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp7_ = image_menu_item_new (ICONS_NEW, _tmp6_);
  ^~~~~~
menu-bar.c:426:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  _tmp8_ = image_menu_item_new (ICONS_QUIT, NULL);
  ^~~~~~

parameter-box.c: In function 'parameter_box_get_type':
parameter-box.c:102:3: warning: 'gtk_hbox_get_type' is deprecated [-Wdeprecated-declarations]
   parameter_box_type_id = g_type_register_static (gtk_hbox_get_type (), "ParameterBox", &g_define_type_info, 0);
   ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:258:0,
                 from parameter-box.c:7:
/usr/include/gtk-3.0/gtk/deprecated/gtkhbox.h:61:13: note: declared here
 GType       gtk_hbox_get_type (void) G_GNUC_CONST;
             ^~~~~~~~~~~~~~~~~

Waf: Leaving directory `/home/filiperosset/rpmbuild/extras/fourterm/fourterm-1.0.6/build'
Build failed
 -> task in 'fourterm' failed with exit status 1 (run with -v to display more information)
erro: Status de saída de /var/tmp/rpm-tmp.ogc9FK inválido (%build)

Erros na construção do RPM:
    bogus date in %changelog: Sun Mar 26 2012 Lukas Zapletal <lzap+git@redhat.com> 1.0.0-1
    Status de saída de /var/tmp/rpm-tmp.ogc9FK inválido (%build)
Could not execute local: Non zero exit
[filiperosset@rosset-laptop fourterm]$

**Comment by lzap** [comment]
Thanks for report, I currently don't have much time to work on fourterm. Can take a look later this week, unless you send a patch :-)

**Comment by lzap** [comment]
I don't believe anyone is using FourTerm now, I will let it to be pushed out of Fedora.
